/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedMarketplaceRouteImport } from './routes/_authed/marketplace'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiBillingClerkWebhookRouteImport } from './routes/api/billing/clerk-webhook'
import { Route as AuthedSandboxesSandboxIdRouteImport } from './routes/_authed/sandboxes/$sandboxId'
import { Route as AuthedMarketplaceAgentSlugRouteImport } from './routes/_authed/marketplace/$agentSlug'
import { Route as ApiX402SandboxesCreateRouteImport } from './routes/api/x402/sandboxes/create'
import { Route as AuthedMarketplaceDraftsAgentIdRouteImport } from './routes/_authed/marketplace/drafts/$agentId'
import { Route as ApiX402SandboxesSandboxIdWebTerminalRouteImport } from './routes/api/x402/sandboxes/$sandboxId/web-terminal'
import { Route as ApiX402SandboxesSandboxIdSshRouteImport } from './routes/api/x402/sandboxes/$sandboxId/ssh'
import { Route as ApiX402SandboxesSandboxIdRestartRouteImport } from './routes/api/x402/sandboxes/$sandboxId/restart'
import { Route as ApiX402SandboxesSandboxIdPreviewRouteImport } from './routes/api/x402/sandboxes/$sandboxId/preview'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMarketplaceRoute = AuthedMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiBillingClerkWebhookRoute = ApiBillingClerkWebhookRouteImport.update({
  id: '/api/billing/clerk-webhook',
  path: '/api/billing/clerk-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSandboxesSandboxIdRoute =
  AuthedSandboxesSandboxIdRouteImport.update({
    id: '/sandboxes/$sandboxId',
    path: '/sandboxes/$sandboxId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedMarketplaceAgentSlugRoute =
  AuthedMarketplaceAgentSlugRouteImport.update({
    id: '/$agentSlug',
    path: '/$agentSlug',
    getParentRoute: () => AuthedMarketplaceRoute,
  } as any)
const ApiX402SandboxesCreateRoute = ApiX402SandboxesCreateRouteImport.update({
  id: '/api/x402/sandboxes/create',
  path: '/api/x402/sandboxes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMarketplaceDraftsAgentIdRoute =
  AuthedMarketplaceDraftsAgentIdRouteImport.update({
    id: '/drafts/$agentId',
    path: '/drafts/$agentId',
    getParentRoute: () => AuthedMarketplaceRoute,
  } as any)
const ApiX402SandboxesSandboxIdWebTerminalRoute =
  ApiX402SandboxesSandboxIdWebTerminalRouteImport.update({
    id: '/api/x402/sandboxes/$sandboxId/web-terminal',
    path: '/api/x402/sandboxes/$sandboxId/web-terminal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiX402SandboxesSandboxIdSshRoute =
  ApiX402SandboxesSandboxIdSshRouteImport.update({
    id: '/api/x402/sandboxes/$sandboxId/ssh',
    path: '/api/x402/sandboxes/$sandboxId/ssh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiX402SandboxesSandboxIdRestartRoute =
  ApiX402SandboxesSandboxIdRestartRouteImport.update({
    id: '/api/x402/sandboxes/$sandboxId/restart',
    path: '/api/x402/sandboxes/$sandboxId/restart',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiX402SandboxesSandboxIdPreviewRoute =
  ApiX402SandboxesSandboxIdPreviewRouteImport.update({
    id: '/api/x402/sandboxes/$sandboxId/preview',
    path: '/api/x402/sandboxes/$sandboxId/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/marketplace': typeof AuthedMarketplaceRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/marketplace/$agentSlug': typeof AuthedMarketplaceAgentSlugRoute
  '/sandboxes/$sandboxId': typeof AuthedSandboxesSandboxIdRoute
  '/api/billing/clerk-webhook': typeof ApiBillingClerkWebhookRoute
  '/marketplace/drafts/$agentId': typeof AuthedMarketplaceDraftsAgentIdRoute
  '/api/x402/sandboxes/create': typeof ApiX402SandboxesCreateRoute
  '/api/x402/sandboxes/$sandboxId/preview': typeof ApiX402SandboxesSandboxIdPreviewRoute
  '/api/x402/sandboxes/$sandboxId/restart': typeof ApiX402SandboxesSandboxIdRestartRoute
  '/api/x402/sandboxes/$sandboxId/ssh': typeof ApiX402SandboxesSandboxIdSshRoute
  '/api/x402/sandboxes/$sandboxId/web-terminal': typeof ApiX402SandboxesSandboxIdWebTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/marketplace': typeof AuthedMarketplaceRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/marketplace/$agentSlug': typeof AuthedMarketplaceAgentSlugRoute
  '/sandboxes/$sandboxId': typeof AuthedSandboxesSandboxIdRoute
  '/api/billing/clerk-webhook': typeof ApiBillingClerkWebhookRoute
  '/marketplace/drafts/$agentId': typeof AuthedMarketplaceDraftsAgentIdRoute
  '/api/x402/sandboxes/create': typeof ApiX402SandboxesCreateRoute
  '/api/x402/sandboxes/$sandboxId/preview': typeof ApiX402SandboxesSandboxIdPreviewRoute
  '/api/x402/sandboxes/$sandboxId/restart': typeof ApiX402SandboxesSandboxIdRestartRoute
  '/api/x402/sandboxes/$sandboxId/ssh': typeof ApiX402SandboxesSandboxIdSshRoute
  '/api/x402/sandboxes/$sandboxId/web-terminal': typeof ApiX402SandboxesSandboxIdWebTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/marketplace': typeof AuthedMarketplaceRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/marketplace/$agentSlug': typeof AuthedMarketplaceAgentSlugRoute
  '/_authed/sandboxes/$sandboxId': typeof AuthedSandboxesSandboxIdRoute
  '/api/billing/clerk-webhook': typeof ApiBillingClerkWebhookRoute
  '/_authed/marketplace/drafts/$agentId': typeof AuthedMarketplaceDraftsAgentIdRoute
  '/api/x402/sandboxes/create': typeof ApiX402SandboxesCreateRoute
  '/api/x402/sandboxes/$sandboxId/preview': typeof ApiX402SandboxesSandboxIdPreviewRoute
  '/api/x402/sandboxes/$sandboxId/restart': typeof ApiX402SandboxesSandboxIdRestartRoute
  '/api/x402/sandboxes/$sandboxId/ssh': typeof ApiX402SandboxesSandboxIdSshRoute
  '/api/x402/sandboxes/$sandboxId/web-terminal': typeof ApiX402SandboxesSandboxIdWebTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/profile'
    | '/marketplace/$agentSlug'
    | '/sandboxes/$sandboxId'
    | '/api/billing/clerk-webhook'
    | '/marketplace/drafts/$agentId'
    | '/api/x402/sandboxes/create'
    | '/api/x402/sandboxes/$sandboxId/preview'
    | '/api/x402/sandboxes/$sandboxId/restart'
    | '/api/x402/sandboxes/$sandboxId/ssh'
    | '/api/x402/sandboxes/$sandboxId/web-terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/marketplace'
    | '/profile'
    | '/marketplace/$agentSlug'
    | '/sandboxes/$sandboxId'
    | '/api/billing/clerk-webhook'
    | '/marketplace/drafts/$agentId'
    | '/api/x402/sandboxes/create'
    | '/api/x402/sandboxes/$sandboxId/preview'
    | '/api/x402/sandboxes/$sandboxId/restart'
    | '/api/x402/sandboxes/$sandboxId/ssh'
    | '/api/x402/sandboxes/$sandboxId/web-terminal'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/marketplace'
    | '/_authed/profile'
    | '/_authed/marketplace/$agentSlug'
    | '/_authed/sandboxes/$sandboxId'
    | '/api/billing/clerk-webhook'
    | '/_authed/marketplace/drafts/$agentId'
    | '/api/x402/sandboxes/create'
    | '/api/x402/sandboxes/$sandboxId/preview'
    | '/api/x402/sandboxes/$sandboxId/restart'
    | '/api/x402/sandboxes/$sandboxId/ssh'
    | '/api/x402/sandboxes/$sandboxId/web-terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiBillingClerkWebhookRoute: typeof ApiBillingClerkWebhookRoute
  ApiX402SandboxesCreateRoute: typeof ApiX402SandboxesCreateRoute
  ApiX402SandboxesSandboxIdPreviewRoute: typeof ApiX402SandboxesSandboxIdPreviewRoute
  ApiX402SandboxesSandboxIdRestartRoute: typeof ApiX402SandboxesSandboxIdRestartRoute
  ApiX402SandboxesSandboxIdSshRoute: typeof ApiX402SandboxesSandboxIdSshRoute
  ApiX402SandboxesSandboxIdWebTerminalRoute: typeof ApiX402SandboxesSandboxIdWebTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketplace': {
      id: '/_authed/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthedMarketplaceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/billing/clerk-webhook': {
      id: '/api/billing/clerk-webhook'
      path: '/api/billing/clerk-webhook'
      fullPath: '/api/billing/clerk-webhook'
      preLoaderRoute: typeof ApiBillingClerkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sandboxes/$sandboxId': {
      id: '/_authed/sandboxes/$sandboxId'
      path: '/sandboxes/$sandboxId'
      fullPath: '/sandboxes/$sandboxId'
      preLoaderRoute: typeof AuthedSandboxesSandboxIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/marketplace/$agentSlug': {
      id: '/_authed/marketplace/$agentSlug'
      path: '/$agentSlug'
      fullPath: '/marketplace/$agentSlug'
      preLoaderRoute: typeof AuthedMarketplaceAgentSlugRouteImport
      parentRoute: typeof AuthedMarketplaceRoute
    }
    '/api/x402/sandboxes/create': {
      id: '/api/x402/sandboxes/create'
      path: '/api/x402/sandboxes/create'
      fullPath: '/api/x402/sandboxes/create'
      preLoaderRoute: typeof ApiX402SandboxesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/marketplace/drafts/$agentId': {
      id: '/_authed/marketplace/drafts/$agentId'
      path: '/drafts/$agentId'
      fullPath: '/marketplace/drafts/$agentId'
      preLoaderRoute: typeof AuthedMarketplaceDraftsAgentIdRouteImport
      parentRoute: typeof AuthedMarketplaceRoute
    }
    '/api/x402/sandboxes/$sandboxId/web-terminal': {
      id: '/api/x402/sandboxes/$sandboxId/web-terminal'
      path: '/api/x402/sandboxes/$sandboxId/web-terminal'
      fullPath: '/api/x402/sandboxes/$sandboxId/web-terminal'
      preLoaderRoute: typeof ApiX402SandboxesSandboxIdWebTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/sandboxes/$sandboxId/ssh': {
      id: '/api/x402/sandboxes/$sandboxId/ssh'
      path: '/api/x402/sandboxes/$sandboxId/ssh'
      fullPath: '/api/x402/sandboxes/$sandboxId/ssh'
      preLoaderRoute: typeof ApiX402SandboxesSandboxIdSshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/sandboxes/$sandboxId/restart': {
      id: '/api/x402/sandboxes/$sandboxId/restart'
      path: '/api/x402/sandboxes/$sandboxId/restart'
      fullPath: '/api/x402/sandboxes/$sandboxId/restart'
      preLoaderRoute: typeof ApiX402SandboxesSandboxIdRestartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x402/sandboxes/$sandboxId/preview': {
      id: '/api/x402/sandboxes/$sandboxId/preview'
      path: '/api/x402/sandboxes/$sandboxId/preview'
      fullPath: '/api/x402/sandboxes/$sandboxId/preview'
      preLoaderRoute: typeof ApiX402SandboxesSandboxIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedMarketplaceRouteChildren {
  AuthedMarketplaceAgentSlugRoute: typeof AuthedMarketplaceAgentSlugRoute
  AuthedMarketplaceDraftsAgentIdRoute: typeof AuthedMarketplaceDraftsAgentIdRoute
}

const AuthedMarketplaceRouteChildren: AuthedMarketplaceRouteChildren = {
  AuthedMarketplaceAgentSlugRoute: AuthedMarketplaceAgentSlugRoute,
  AuthedMarketplaceDraftsAgentIdRoute: AuthedMarketplaceDraftsAgentIdRoute,
}

const AuthedMarketplaceRouteWithChildren =
  AuthedMarketplaceRoute._addFileChildren(AuthedMarketplaceRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMarketplaceRoute: typeof AuthedMarketplaceRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedSandboxesSandboxIdRoute: typeof AuthedSandboxesSandboxIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMarketplaceRoute: AuthedMarketplaceRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedSandboxesSandboxIdRoute: AuthedSandboxesSandboxIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiBillingClerkWebhookRoute: ApiBillingClerkWebhookRoute,
  ApiX402SandboxesCreateRoute: ApiX402SandboxesCreateRoute,
  ApiX402SandboxesSandboxIdPreviewRoute: ApiX402SandboxesSandboxIdPreviewRoute,
  ApiX402SandboxesSandboxIdRestartRoute: ApiX402SandboxesSandboxIdRestartRoute,
  ApiX402SandboxesSandboxIdSshRoute: ApiX402SandboxesSandboxIdSshRoute,
  ApiX402SandboxesSandboxIdWebTerminalRoute:
    ApiX402SandboxesSandboxIdWebTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
